/**
 *
 * @author up781587, up769535, up743299
 */
import java.awt.HeadlessException;
import javax.swing.*;
import java.text.DecimalFormat;

public class UserInterface extends javax.swing.JFrame {
private String boxType;
private double total;
private double length;
private double height;
private double width;
    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
        spinQuantity.setValue(1);
        spinGrade.setValue(1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelDimensions = new javax.swing.JPanel();
        textHeight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textWidth = new javax.swing.JTextField();
        textLength = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spinGrade = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        spinQuantity = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelExtras = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboColour = new javax.swing.JComboBox<>();
        checkBottom = new javax.swing.JCheckBox();
        checkCorner = new javax.swing.JCheckBox();
        checkTop = new javax.swing.JCheckBox();
        btnAddItem = new javax.swing.JButton();
        btnClearOrder = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnClearForm = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        labelTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelOrders = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 240, 241));

        panelBackground.setBackground(new java.awt.Color(245, 245, 245));
        panelBackground.setToolTipText("");

        panelDimensions.setBackground(new java.awt.Color(236, 240, 241));
        panelDimensions.setBorder(javax.swing.BorderFactory.createTitledBorder("Inputs"));
        panelDimensions.setForeground(new java.awt.Color(240, 240, 240));
        panelDimensions.setToolTipText("");
        panelDimensions.setName("enterDimensions"); // NOI18N

        textHeight.setForeground(new java.awt.Color(77, 77, 77));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Length");

        textWidth.setForeground(new java.awt.Color(77, 77, 77));

        textLength.setForeground(new java.awt.Color(77, 77, 77));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Width");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Grade:");

        spinGrade.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Quantity:");

        spinQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Height");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("    X");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("    X");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelDimensionsLayout = new javax.swing.GroupLayout(panelDimensions);
        panelDimensions.setLayout(panelDimensionsLayout);
        panelDimensionsLayout.setHorizontalGroup(
            panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDimensionsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(panelDimensionsLayout.createSequentialGroup()
                        .addGroup(panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDimensionsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDimensionsLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(spinGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDimensionsLayout.createSequentialGroup()
                        .addGroup(panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDimensionsLayout.createSequentialGroup()
                                .addComponent(textLength, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(textHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDimensionsLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(spinQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDimensionsLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDimensionsLayout.setVerticalGroup(
            panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDimensionsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLength, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDimensionsLayout.createSequentialGroup()
                        .addGroup(panelDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDimensionsLayout.createSequentialGroup()
                        .addComponent(spinQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        panelExtras.setBackground(new java.awt.Color(236, 240, 241));
        panelExtras.setBorder(javax.swing.BorderFactory.createTitledBorder("Extras"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Reinforced Bottom");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Colour");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Sealable Top");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Reinforced Corners");

        comboColour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));

        javax.swing.GroupLayout panelExtrasLayout = new javax.swing.GroupLayout(panelExtras);
        panelExtras.setLayout(panelExtrasLayout);
        panelExtrasLayout.setHorizontalGroup(
            panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtrasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelExtrasLayout.createSequentialGroup()
                            .addGroup(panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(106, 106, 106))
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(panelExtrasLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addGroup(panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBottom)
                    .addComponent(checkCorner)
                    .addComponent(checkTop)
                    .addComponent(comboColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelExtrasLayout.setVerticalGroup(
            panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelExtrasLayout.createSequentialGroup()
                        .addGroup(panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelExtrasLayout.createSequentialGroup()
                                .addGroup(panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(checkBottom)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkCorner))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkTop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnClearOrder.setText("Clear Order");
        btnClearOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearOrderActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("FlexBox Ordering System");

        btnClearForm.setText("Reset Form");
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(236, 240, 241));

        labelTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotal.setText("£0.00");
        labelTotal.setAlignmentX(1.0F);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Total:");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOrders.setEditable(false);
        panelOrders.setColumns(20);
        panelOrders.setRows(5);
        panelOrders.setText("                                \n                              Receipt\n--------------------------------------------------------------");
        jScrollPane1.setViewportView(panelOrders);

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClearOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelExtras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDimensions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12))))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(panelDimensions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(268, 268, 268))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Starts validation and stored inputs of the box
     * @param evt 
     */
    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {
        //gets values from fields in form
        double size;
        int grade = (int)spinGrade.getValue();
        int color = comboColour.getSelectedIndex();
        boolean sealable = checkTop.isSelected();
        boolean bottom = checkBottom.isSelected();
        boolean corner = checkCorner.isSelected();
        int quantity = (int)spinQuantity.getValue();

        //validation to avoid number format exception
        try{
            width = Double.parseDouble(textWidth.getText());
            length = Double.parseDouble(textLength.getText());
            height = Double.parseDouble(textHeight.getText());

            //checking if size is within required range 0.5 to 10
            if (width < 0.5 || width > 10 || length < 0.5 || length > 10 || height < 0.5 || height > 10) {
                JOptionPane.showMessageDialog(null, "The width/length/height must be a number between 0.5M to 10M.",
                    "Invalid Input", JOptionPane.ERROR_MESSAGE);
            }

            else {
                  //working out the size of the box
                  size = ((width * length) + (width * height) + (length * height)) * 2;
                  newBox(grade, color, bottom, corner, sealable, size, quantity);
            }

        //return error if exception found
        }catch(NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "The size must be a positive number.",
                    "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * Creates a new box with the values passed
     * @param grade grade of the box
     * @param colour number of colours
     * @param bottom if reinforced bottoms or not
     * @param corner if reinforced corner or not
     * @param sealable if sealable top or not
     * @param size size of box (w*l*h)
     * @param quantity  how many boxes
     */
    public void newBox(int grade, int colour, boolean bottom, boolean corner,
                    boolean sealable, double size, int quantity){

            double price;

            //checks which type the box is by using if statements to match requirements
            if(colour == 0 && !bottom && !corner && grade >= 1 && grade <= 3){
                    Box box = new BoxType1(grade, size, sealable); //creates box type 1
                    price = box.getPrice(); //Gets price from abstract method
                    boxType = "1";
                    printReceipt(boxType, size, grade, colour, bottom, corner, sealable, quantity, price);
            }else if(colour == 1 && !bottom && !corner && grade >= 2 && grade <= 4){
                    Box box = new BoxType2(grade, size, sealable ); //creates box type 2
                    price = box.getPrice(); //Gets price from abstract method
                    boxType = "2";
                    printReceipt(boxType, size, grade, colour, bottom, corner, sealable, quantity, price);
            }else if(colour == 2 && !bottom && !corner && grade >= 2 && grade <= 5){
                    Box box = new BoxType3(grade, size, sealable); //creates box type 3
                    price = box.getPrice(); //Gets price from abstract method
                    boxType = "3";
                    printReceipt(boxType, size, grade, colour, bottom, corner, sealable, quantity, price);
            }else if(colour == 2 && bottom && !corner && grade >= 2 && grade <= 5){
                    Box box = new BoxType4(grade, size, sealable); //creates box type 4
                    price = box.getPrice(); //Gets price from abstract method
                    boxType = "4";
                    printReceipt(boxType, size, grade, colour, bottom, corner, sealable, quantity, price);
            }else if(colour == 2 && bottom && corner && grade >= 3 && grade <= 5){ //creates box type 5
                    Box box = new BoxType5(grade, size, sealable);
                    price = box.getPrice(); //Gets price from abstract method
                    boxType = "5";
                    printReceipt(boxType, size, grade, colour, bottom, corner, sealable, quantity, price);
            }

            // if the box doesn't match any type of box, an error is given to the user with tips
            else {
              JOptionPane.showMessageDialog(null, " Flexbox doesn't produce any boxs that match these "
                      + "requirements. \n \n Tip: Boxes with higher grade allow more extra features "
                      + "(Colours, \n Reinforced Corners, & Reinforced Bottoms).", ""
                              + " Invalid Box, Please Try Again",JOptionPane.ERROR_MESSAGE);
            }
    }

    /**
     * Prints the receipt in the output section
     *
     * @param boxType type of box from 1 to 5
     * @param size size of box
     * @param grade grade of box
     * @param colour how many colours
     * @param bottom if reinforced bottom
     * @param corner if reinforced corner
     * @param sealable if sealable top
     * @param quantity how many boxes
     * @param price price of the box order
     */
    public void printReceipt(String boxType, double size, int grade, int colour,
            boolean bottom, boolean corner, boolean sealable, int quantity, double price) {
        panelOrders.setText(panelOrders.getText() + "\n Box Type: " + boxType); //For demo and debugging purposes
        panelOrders.setText(panelOrders.getText() + "\n Size: " + width + " X " + length + " X " + height);
        panelOrders.setText(panelOrders.getText() + "\n Grade: " + grade);
        panelOrders.setText(panelOrders.getText() + "\n Colour: " + colour);

        if (bottom) { panelOrders.setText(panelOrders.getText() + "\n     Reinforced Bottom Included"); }

        if (corner) { panelOrders.setText(panelOrders.getText() + "\n     Reinforced Corner Included"); }

        if (sealable) { panelOrders.setText(panelOrders.getText() + "\n     Sealable Top Included"); }

        panelOrders.setText(panelOrders.getText() + "\n Quantity: " + quantity);
        price = price * quantity;
        DecimalFormat dpForm = new DecimalFormat("0.00");//rounds the number to 2 decimal places
        panelOrders.setText(panelOrders.getText() + "\n Box Total: £" + dpForm.format(price) + "\n");
        panelOrders.setText(panelOrders.getText() + "--------------------------------------------------------------\n");

        total = price + total;
        total = (double) (Math.round(total*100))/100;
        labelTotal.setText("£" + (dpForm.format(total))); 

    }

    /**
     * Clears the orders and resets the total
     * @param evt 
     */
    private void btnClearOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearOrderActionPerformed
        // clears order
        panelOrders.setText("");
        total = 0;
        labelTotal.setText("");
    }//GEN-LAST:event_btnClearOrderActionPerformed

    /** Resets the form by clearing all input fields
     * 
     * @param evt 
     */
    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
        //reset entire form
        textWidth.setText("");
        textLength.setText("");
        textHeight.setText("");
        checkBottom.setSelected(false);
        checkCorner.setSelected(false);
        checkTop.setSelected(false);
        spinQuantity.setValue(1);
        spinGrade.setValue(1);
        comboColour.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnClearOrder;
    private javax.swing.JCheckBox checkBottom;
    private javax.swing.JCheckBox checkCorner;
    private javax.swing.JCheckBox checkTop;
    private javax.swing.JComboBox<String> comboColour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelDimensions;
    private javax.swing.JPanel panelExtras;
    private javax.swing.JTextArea panelOrders;
    private javax.swing.JSpinner spinGrade;
    private javax.swing.JSpinner spinQuantity;
    private javax.swing.JTextField textHeight;
    private javax.swing.JTextField textLength;
    private javax.swing.JTextField textWidth;
    // End of variables declaration//GEN-END:variables


}
